// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhsuRluNJQrMdMgsKzJNBif_cd2H-yvk',
    appId: '1:452787590635:web:4df78b0be65d3190b6b5ae',
    messagingSenderId: '452787590635',
    projectId: 'fir-46cca',
    authDomain: 'fir-46cca.firebaseapp.com',
    storageBucket: 'fir-46cca.appspot.com',
    measurementId: 'G-Y0RZ7H8KDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb0l4i9d5Gk1ARcTosCl8XDf9AGJu0mc0',
    appId: '1:452787590635:android:4f9b87c36f510175b6b5ae',
    messagingSenderId: '452787590635',
    projectId: 'fir-46cca',
    storageBucket: 'fir-46cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZs18Mk1ZZDC9KjdsAwmj660OuEaokoIA',
    appId: '1:452787590635:ios:2a49daf1c073678cb6b5ae',
    messagingSenderId: '452787590635',
    projectId: 'fir-46cca',
    storageBucket: 'fir-46cca.appspot.com',
    iosBundleId: 'com.example.mlsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZs18Mk1ZZDC9KjdsAwmj660OuEaokoIA',
    appId: '1:452787590635:ios:b6230a2ef3bb1763b6b5ae',
    messagingSenderId: '452787590635',
    projectId: 'fir-46cca',
    storageBucket: 'fir-46cca.appspot.com',
    iosBundleId: 'com.example.mlsc.RunnerTests',
  );
}
